# Laboratorio 2

In [3]:
import numpy as np
from scipy import linalg

## Ejercicio 1

Dados dos NumPy array, `x` e `y` unidimensionales, construye su matriz de Cauchy `C`tal que 

(1 punto)

$$
    c_{ij} = \frac{1}{x_i - y_j}
$$

In [87]:
np.empty(shape=(3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
def cauchy_matrix(x, y):
    m = x.shape[0]
    n = y.shape[0]
    C = np.empty(shape=(m, n))
    for i in range(m):# FIX ME 
        for j in range(n):# FIX ME #
                C[i,j]=1/(x[i]+y[j])# FIX ME #
    return C

In [31]:
x = np.arange(10, 101, 10)
y = np.arange(5)
cauchy_matrix(x, y)

array([[0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
       [0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667],
       [0.03333333, 0.03225806, 0.03125   , 0.03030303, 0.02941176],
       [0.025     , 0.02439024, 0.02380952, 0.02325581, 0.02272727],
       [0.02      , 0.01960784, 0.01923077, 0.01886792, 0.01851852],
       [0.01666667, 0.01639344, 0.01612903, 0.01587302, 0.015625  ],
       [0.01428571, 0.01408451, 0.01388889, 0.01369863, 0.01351351],
       [0.0125    , 0.01234568, 0.01219512, 0.01204819, 0.01190476],
       [0.01111111, 0.01098901, 0.01086957, 0.01075269, 0.0106383 ],
       [0.01      , 0.00990099, 0.00980392, 0.00970874, 0.00961538]])

## Ejercicio 2

(1 punto)

Implementa la multiplicación matricial a través de dos ciclos `for`. Verifica que tu implementación está correcta y luego compara los tiempos de tu implementación versus la de NumPy.

In [32]:
def my_mul(A, B):   # defino funcion
    m, n = A.shape  # m,n con dimension de A .. estoy descomprimiendo las dimensiones A
    p, q = B.shape  #p.q con dimension de B .. estoy descomprimiendo las dimensiones A
    if n != p:       #si n es distinto de p tira error
        raise ValueError("Las dimensiones de las matrices no calzan!")
    C = np.empty(shape=(m,q))  #creo una matriz vacia
    for i in range(m):# Itero todas las filas
        for j in range(q): # Itero todas las columnas
            C[i, j] = np.sum(A[i,:] * B[:,j]) # FIX ME # HINT: Recuerda la multiplicacion elemento a elemento y la función np.sum
                                            #No se como mult. elemento a elemento y se suman todos
    
    return C

In [33]:
A = np.arange(15).reshape(-1, 5)
B = np.arange(20).reshape(5, -1)
my_mul(A, B)

array([[120., 130., 140., 150.],
       [320., 355., 390., 425.],
       [520., 580., 640., 700.]])

In [34]:
# Validation
np.allclose(my_mul(A, B), A @ B)

True

In [315]:
%%timeit
my_mul(A, B)

87.8 µs ± 1.49 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [317]:
%%timeit
A @ B

1.24 µs ± 25 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [35]:
A @ B

array([[120, 130, 140, 150],
       [320, 355, 390, 425],
       [520, 580, 640, 700]])

## Ejercicio 3

(1 punto)

Crea una función que imprima todos los bloques contiguos de tamaño $3 \times 3$ para una matriz de $5 \times 5$.
Hint: Deben ser 9 bloques!

In [ ]:
#Generar bloques de 3x3 dentro de la matriz 5x5, deben ser 9 bloques, revisar slicing

In [92]:
def three_times_three_blocks(A):
    m, n = A.shape
    counter = 1
    for i in range(0,3):
        for j in range(0,3):
            block = A[i:3+i,j:3+j]
            print(f"Block {counter}:")
            print(block)
            print("\n")
            counter += 1

In [93]:
A = np.arange(1, 26).reshape(5, 5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [94]:
three_times_three_blocks(A)

Block 1:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


Block 2:
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


Block 3:
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


Block 4:
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


Block 5:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


Block 6:
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


Block 7:
[[11 12 13]
 [16 17 18]
 [21 22 23]]


Block 8:
[[12 13 14]
 [17 18 19]
 [22 23 24]]


Block 9:
[[13 14 15]
 [18 19 20]
 [23 24 25]]




## Ejercicio 4

(1 punto)

Has tu propio implementación de la matriz de Hilbert de orden $n$ y luego compara los tiempos de ejecución versus la función [`scipy.linalg.hilbert`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.hilbert.html#scipy.linalg.hilbert). Finalmente, verifica que la inversa de tu implementación (utilizando `linalg.inv`) es idéntica a la obtenida con la función [`scipy.linalg.invhilbert`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.invhilbert.html#scipy.linalg.invhilbert).

In [40]:
def my_hilbert(n):
    H = np.empty((n, n))    #Returns the n by n array with entries h[i,j] = 1 / (i + j + 1).
    for i in range(n):# FIX ME 
        for j in range(n):# FIX ME #
                H[i,j] = 1 / (i + j + 1)  # C[i,j]=1/(x[i]+y[j])
    return H

In [96]:
my_hilbert(3)

array([[1.        , 0.5       , 0.33333333],
       [0.5       , 0.33333333, 0.25      ],
       [0.33333333, 0.25      , 0.2       ]])

In [109]:
n = 10
np.allclose(my_hilbert(n), linalg.hilbert(n))

True

In [110]:
%timeit my_hilbert(n)

24.6 µs ± 653 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [111]:
%timeit linalg.hilbert(n)

20.3 µs ± 793 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [112]:
# Verificacion inversas

np.allclose(linalg.inv(my_hilbert(n)),linalg.invhilbert(n))

False

Vuelve a probar pero con $n=10$. ¿Cambia algo? ¿Por qué podría ser?

__Respuesta:__  # FIX ME PLEASE #